var a = 10
document.write("Result: ");
document.write("<br>");
document.write(" the value of a is:",a);
document.write ("<br>");

var ++a;
document.write("The value of ++a is:",a);
document.write("<br>");
document.write(" now the value of a is:",a);
document.write ("<br>");


var(a++);
document.write("The value of a++ is:" a);
document.write("<br>");
document.write(" the value of a is:",a);
document.write ("<br>");


a--;
document.write("The value of a-- is: "a);
document.write("<br>");
document.write(" the value of a is:",a);
document.write ("<br>");
